import asyncio
import random
from motor.motor_asyncio import AsyncIOMotorClient
from datetime import datetime, timezone, timedelta

MONGODB_URI = "mongodb://localhost:27017"
DB_NAME = "shophub"

def rand_date():
    days = random.randint(1, 180)
    return (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()

# Real product image pools from DummyJSON CDN (permanently hosted, always work)
CATEGORY_IMAGES = {
    "Electronics": [
        "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp",
    ],
    "Clothing": [
        "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mens-shoes/nike-baseball-cleats/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mens-shoes/puma-future-rider-trainers/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-&-red/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/tops/gray-dress/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/womens-shoes/calvin-klein-heel-shoes/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/womens-shoes/golden-shoes-woman/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sunglasses/classic-sun-glasses/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/thumbnail.webp",
    ],
    "Home & Kitchen": [
        "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/home-decoration/table-lamp/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/kitchen-accessories/boxed-blender/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/kitchen-accessories/microwave-oven/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/kitchen-accessories/electric-stove/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/kitchen-accessories/carbon-steel-wok/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/kitchen-accessories/knife/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/kitchen-accessories/pan/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/kitchen-accessories/silver-pot-with-glass-cap/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/kitchen-accessories/spice-rack/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/kitchen-accessories/hand-blender/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/home-decoration/plant-pot/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/kitchen-accessories/plate/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/kitchen-accessories/glass/thumbnail.webp",
    ],
    "Sports & Outdoors": [
        "https://cdn.dummyjson.com/product-images/sports-accessories/american-football/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/basketball/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-ball/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-bat/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-helmet/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/football/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/golf-ball/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/iron-golf/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/tennis-ball/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/tennis-racket/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/volleyball/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/metal-baseball-bat/thumbnail.webp",
    ],
    "Books": [
        "https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/nescafe-coffee/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/protein-powder/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/rice/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/tissue-paper-box/thumbnail.webp",
    ],
    "Beauty": [
        "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/skin-care/attitude-super-leaves-hand-soap/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/skin-care/olay-ultra-moisture-shea-butter-body-wash/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/skin-care/vaseline-men-body-and-face-lotion/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp",
    ],
    "Toys & Games": [
        "https://cdn.dummyjson.com/product-images/sports-accessories/feather-shuttlecock/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-wicket/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/home-decoration/house-showpiece-plant/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/home-decoration/family-tree-photo-frame/thumbnail.webp",
    ],
    "Automotive": [
        "https://cdn.dummyjson.com/product-images/vehicle/300-touring/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/vehicle/charger-sxt-rwd/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/vehicle/dodge-hornet-gt-plus/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/vehicle/pacifica-touring/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/motorcycle/kawasaki-z800/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/thumbnail.webp",
    ],
    "Grocery": [
        "https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/cooking-oil/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/eggs/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/honey-jar/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/ice-cream/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/juice/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/milk/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/nescafe-coffee/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/soft-drinks/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/strawberry/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/groceries/water/thumbnail.webp",
    ],
    "Gaming": [
        "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/thumbnail.webp",
    ],
    "Office": [
        "https://cdn.dummyjson.com/product-images/laptops/lenovo-yoga-920/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/laptops/huawei-matebook-x-pro/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp",
        "https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp",
    ],
}

# Global counter for cycling through images per category
_img_counters: dict[str, int] = {}

def p(name, desc, price, cat, stock, rating=None, reviews=None):
    """Create a product document with a real product image from CDN."""
    # Get the image pool for this category
    pool = CATEGORY_IMAGES.get(cat, CATEGORY_IMAGES["Electronics"])

    # Cycle through images
    idx = _img_counters.get(cat, 0)
    _img_counters[cat] = idx + 1
    image_url = pool[idx % len(pool)]

    return {
        "name": name,
        "description": desc,
        "price": round(price, 2),
        "category": cat,
        "stock": stock,
        "images": [image_url],
        "average_rating": rating or round(random.uniform(3.8, 5.0), 1),
        "review_count": reviews or random.randint(10, 2500),
        "created_at": rand_date(),
    }

PRODUCTS = [
    # â”€â”€ Electronics (80 products) â”€â”€
    p("Sony WH-1000XM5 Wireless Headphones", "Industry-leading noise cancellation with eight microphones and Auto NC Optimizer. 30-hour battery life.", 398, "Electronics", 50),
    p("Apple MacBook Air 13-inch M3", "Superportable laptop with M3 chip, 18-hour battery, Liquid Retina display, and fanless design.", 1099, "Electronics", 25),
    p("Keychron Q6 Pro Mechanical Keyboard", "Full-sized wireless mechanical keyboard with CNC aluminum body and hot-swappable switches.", 210, "Electronics", 15),
    p("Samsung Odyssey G9 49-inch Monitor", "DQHD 240Hz curved gaming monitor with 1ms response time and G-Sync compatibility.", 1299.99, "Electronics", 10),
    p("Fujifilm X100V Digital Camera", "26.1MP X-Trans CMOS 4 sensor, fixed 23mm f/2 lens, classic rangefinder design.", 1599, "Electronics", 5),
    p("Sonos Era 300 Smart Speaker", "Spatial Audio with Dolby Atmos support. Immersive sound from every direction.", 449, "Electronics", 30),
    p("DJI Mini 4 Pro Drone", "Under 249g, 4K/60fps HDR, omnidirectional obstacle sensing, 34-min flight time.", 959, "Electronics", 12),
    p("Apple iPad Pro 12.9-inch M2", "Liquid Retina XDR display, M2 chip, ProMotion technology, Thunderbolt connectivity.", 1099, "Electronics", 20),
    p("Bose QuietComfort Ultra Earbuds", "Immersive audio with spatial sound, world-class noise cancellation, CustomTune technology.", 299, "Electronics", 40),
    p("LG C3 65-inch OLED 4K TV", "Self-lit OLED pixels, Î±9 Gen6 AI Processor, Dolby Vision & Atmos, webOS 23.", 1499, "Electronics", 8),
    p("Apple Watch Ultra 2", "49mm titanium case, precision dual-frequency GPS, up to 36-hour battery, 100m water resistance.", 799, "Electronics", 18),
    p("Samsung Galaxy S24 Ultra", "200MP camera, Snapdragon 8 Gen 3, built-in S Pen, titanium frame, AI features.", 1299, "Electronics", 22),
    p("Sony A7 IV Mirrorless Camera", "33MP full-frame sensor, 4K 60p video, real-time Eye AF, 10fps burst shooting.", 2498, "Electronics", 6),
    p("Razer DeathAdder V3 Pro Mouse", "63g ultralight, Focus Pro 30K sensor, HyperSpeed wireless, 90-hour battery.", 89.99, "Electronics", 45),
    p("ASUS ROG Strix RTX 4080 GPU", "16GB GDDR6X, Axial-tech fans, DLSS 3, ray tracing, PCIe 4.0.", 1199, "Electronics", 7),
    p("Logitech MX Master 3S Mouse", "8K DPI sensor, MagSpeed scroll, quiet clicks, USB-C, multi-device support.", 99.99, "Electronics", 55),
    p("Apple AirPods Pro 2nd Gen", "Adaptive Audio, personalized spatial audio, USB-C, 6 hours playback.", 249, "Electronics", 60),
    p("Nintendo Switch OLED Model", "7-inch OLED screen, wide adjustable stand, enhanced audio, 64GB storage.", 349, "Electronics", 35),
    p("Dell XPS 15 Laptop", "15.6-inch 3.5K OLED, Intel Core i9, 32GB RAM, 1TB SSD, NVIDIA RTX 4060.", 1999, "Electronics", 10),
    p("Google Pixel 8 Pro", "Tensor G3 chip, 50MP camera with AI, 7 years of updates, 6.7-inch display.", 999, "Electronics", 28),
    p("Canon EOS R6 Mark II", "24.2MP full-frame, 40fps electronic shutter, 6K RAW video, dual card slots.", 2499, "Electronics", 4),
    p("Sennheiser Momentum 4 Wireless", "60-hour battery, adaptive noise cancellation, audiophile-grade sound.", 349, "Electronics", 30),
    p("Apple Mac Mini M2 Pro", "M2 Pro chip, 16GB unified memory, compact desktop, Thunderbolt 4 ports.", 1299, "Electronics", 15),
    p("GoPro HERO12 Black", "5.3K60 video, HyperSmooth 6.0, 10-bit color, waterproof to 33ft.", 399, "Electronics", 25),
    p("Anker 737 Power Bank 24000mAh", "140W bi-directional fast charging, smart digital display, compact design.", 109, "Electronics", 70),
    p("Marshall Stanmore III Speaker", "Iconic design, dynamic loudness, HDMI connectivity, multi-room support.", 379, "Electronics", 20),
    p("Lenovo ThinkPad X1 Carbon Gen 11", "14-inch 2.8K OLED, Intel i7 vPro, 1TB SSD, MIL-STD-810H tested.", 1849, "Electronics", 8),
    p("Sony PlayStation 5 Slim", "4K gaming, 1TB SSD, DualSense controller, ray tracing, 120fps support.", 499, "Electronics", 20),
    p("Jabra Elite 85t Earbuds", "Advanced ANC, 6mm speakers, HearThrough mode, wireless Qi charging.", 179, "Electronics", 40),
    p("ASUS ZenBook 14 OLED", "14-inch 2.8K OLED, Intel Core Ultra 7, 16GB LPDDR5X, NumberPad 2.0.", 999, "Electronics", 14),
    p("Beats Studio Pro Headphones", "Personalized spatial audio, USB-C, 40-hour battery, lossless audio.", 349, "Electronics", 25),
    p("Xbox Series X Console", "12 teraflops, 4K/120fps, 1TB SSD, backward compatible, Quick Resume.", 499, "Electronics", 15),
    p("Corsair K100 RGB Mechanical Keyboard", "OPX optical switches, iCUE control wheel, 44-zone RGB, 4000Hz polling.", 229, "Electronics", 20),
    p("TP-Link Deco XE75 Mesh WiFi 6E", "Tri-band WiFi 6E, 5500 sq ft coverage, 200 devices, AI-driven mesh.", 299, "Electronics", 30),
    p("Samsung 990 Pro 2TB NVMe SSD", "7450MB/s read, PCIe 4.0, heat sink included, RGB lighting.", 179, "Electronics", 50),
    p("Elgato Stream Deck MK.2", "15 customizable LCD keys, multi-actions, plugin ecosystem, detachable USB-C.", 149, "Electronics", 35),
    p("Apple HomePod 2nd Gen", "Room-sensing technology, Siri, Thread smart home hub, spatial audio.", 299, "Electronics", 20),
    p("Rode NT-USB+ Condenser Microphone", "Studio-quality USB mic, internal DSP, headphone monitoring, pop filter.", 169, "Electronics", 30),
    p("Garmin Fenix 7X Solar", "Solar-powered GPS smartwatch, topo maps, multi-sport, 37-day battery.", 899, "Electronics", 10),
    p("Philips Hue Gradient Lightstrip 2m", "Multicolor gradient, Bluetooth & Zigbee, sync with entertainment, 16M colors.", 179, "Electronics", 40),
    p("Synology DS923+ NAS", "4-bay NAS, AMD Ryzen R1600, 4GB DDR4, dual M.2 SSD cache, 2x 1GbE.", 599, "Electronics", 8),
    p("Xiaomi 34-inch Curved Monitor", "34-inch WQHD ultrawide, 144Hz, 1500R curvature, AMD FreeSync, USB-C.", 399, "Electronics", 18),
    p("Audio-Technica ATH-M50x Headphones", "45mm large-aperture drivers, exceptional clarity, foldable design.", 149, "Electronics", 60),
    p("Raspberry Pi 5 8GB Kit", "2.4GHz quad-core, 8GB LPDDR4X, dual 4K display, PCIe 2.0 interface.", 119, "Electronics", 25),
    p("Samsung Galaxy Tab S9 Ultra", "14.6-inch Dynamic AMOLED 2X, Snapdragon 8 Gen 2, S Pen included, IP68.", 1199, "Electronics", 10),
    p("Dyson Zone Headphones", "Active noise cancellation with air purification visor, MyDyson app control.", 699, "Electronics", 6),
    p("Shure SM7B Microphone", "Dynamic cardioid mic, flat wide-range frequency response, broadcast quality.", 399, "Electronics", 15),
    p("Meta Quest 3 128GB VR Headset", "Mixed reality, Snapdragon XR2 Gen 2, pancake lenses, full-color passthrough.", 499, "Electronics", 20),
    p("WD Black SN850X 4TB NVMe", "7300MB/s read, PCIe Gen4, heatsink, game mode 2.0, predictive loading.", 349, "Electronics", 25),
    p("Alienware AW3423DWF Monitor", "34-inch QD-OLED, 165Hz, 0.1ms, Dolby Vision HDR, AMD FreeSync Premium Pro.", 1099, "Electronics", 7),
    p("Anker Soundcore Space A40 Earbuds", "Adaptive ANC, 50-hour battery, LDAC, multipoint connection, IPX4.", 79, "Electronics", 80),
    p("Creality Ender-3 V3 3D Printer", "Core XZ structure, 600mm/s max speed, auto-leveling, direct drive extruder.", 289, "Electronics", 12),
    p("TP-Link Tapo C420S2 Security Camera", "2K QHD, wire-free, starlight sensor, 180-day battery, smart AI detection.", 149, "Electronics", 35),
    p("Kindle Paperwhite Signature Edition", "6.8-inch 300ppi display, wireless charging, 32GB, auto-adjusting light.", 189, "Electronics", 40),
    p("JBL Charge 5 Portable Speaker", "IP67 waterproof, 20-hour battery, PartyBoost, dual bass radiators.", 179, "Electronics", 50),
    p("Crucial T700 2TB PCIe 5.0 SSD", "12400MB/s read, DirectStorage optimized, heatsink included.", 249, "Electronics", 15),
    p("NVIDIA Shield TV Pro", "4K HDR streaming, Tegra X1+, Dolby Vision & Atmos, AI upscaling, GeForce NOW.", 199, "Electronics", 20),
    p("Ember Temperature Control Mug 2", "App-controlled temperature, 80-min battery, LED indicator, 14oz capacity.", 149, "Electronics", 35),
    p("Insta360 X4 360-degree Camera", "8K30 360-degree video, FlowState stabilization, invisible selfie stick effect.", 499, "Electronics", 10),
    p("Edifier S3000Pro Bookshelf Speakers", "Planar magnetic tweeters, 256W RMS, Bluetooth 5.0, balanced XLR input.", 799, "Electronics", 8),

    # â”€â”€ Clothing (55 products) â”€â”€
    p("Nike Air Max 270 Sneakers", "Lifestyle sneaker with the tallest Air unit yet, breathable mesh upper, foam midsole.", 150, "Clothing", 80),
    p("Levi's 501 Original Fit Jeans", "The original blue jean since 1873. Button fly, straight leg, 100% cotton denim.", 69.50, "Clothing", 100),
    p("Patagonia Better Sweater Jacket", "Made from 100% recycled polyester fleece, Fair Trade Certified sewn.", 139, "Clothing", 40),
    p("Adidas Ultraboost Light Running Shoes", "Light BOOST midsole, Primeknit+ upper, Continental rubber outsole.", 190, "Clothing", 60),
    p("The North Face 1996 Retro Nuptse Jacket", "700-fill goose down, water-resistant DWR finish, iconic baffled design.", 330, "Clothing", 20),
    p("Ray-Ban Wayfarer Classic Sunglasses", "Iconic acetate frame, polarized G-15 lenses, UV400 protection.", 163, "Clothing", 70),
    p("Uniqlo Ultra Light Down Vest", "Premium down insulation, water-repellent, pocketable design, 64g ultralight.", 59.90, "Clothing", 90),
    p("New Balance 990v6 Made in USA", "Premium suede and mesh upper, ENCAP midsole, Vibram outsole.", 199.99, "Clothing", 35),
    p("Arc'teryx Atom LT Hoody", "Coreloft insulation, Tyono shell, breathable side panels, packable.", 259, "Clothing", 18),
    p("Champion Reverse Weave Hoodie", "Heavyweight fleece, ribbed side panels to reduce shrinkage, iconic C logo.", 65, "Clothing", 100),
    p("Dr. Martens 1460 Boots", "Smooth leather, AirWair bouncing sole, Goodyear welt, iconic yellow stitching.", 170, "Clothing", 40),
    p("Carhartt WIP Chase Sweatshirt", "Heavyweight cotton blend, embroidered logo, relaxed fit, ribbed trims.", 89, "Clothing", 55),
    p("Columbia Omni-Heat Infinity Jacket", "Gold-dot thermal reflective lining, waterproof, 650-fill down insulation.", 250, "Clothing", 22),
    p("Vans Old Skool Classic Sneakers", "Canvas and suede upper, signature side stripe, waffle rubber outsole.", 70, "Clothing", 120),
    p("Calvin Klein Cotton Stretch Boxer Briefs 3-Pack", "Signature waistband, cotton stretch blend, contour pouch, 3-pack value.", 42.50, "Clothing", 150),
    p("Herschel Supply Classic Backpack XL", "30L capacity, padded laptop sleeve, front storage pocket, signature striped liner.", 74.99, "Clothing", 45),
    p("AllBirds Tree Runner Sneakers", "Eucalyptus fiber upper, SweetFoam sole, carbon neutral, machine washable.", 98, "Clothing", 60),
    p("Polo Ralph Lauren Classic Fit Polo", "Signature mesh polo, ribbed collar and armbands, iconic pony embroidery.", 98.50, "Clothing", 80),
    p("FjÃ¤llrÃ¤ven KÃ¥nken Classic Backpack", "Vinylon F fabric, dual handles, padded shoulder straps, 16L capacity.", 80, "Clothing", 50),
    p("Nike Dri-FIT Running T-Shirt", "Moisture-wicking fabric, breathable mesh panels, reflective details.", 35, "Clothing", 200),
    p("Timberland 6-Inch Premium Boots", "Waterproof nubuck leather, padded collar, anti-fatigue footbed, lug outsole.", 198, "Clothing", 30),
    p("Tommy Hilfiger Essential Down Jacket", "Down-filled puffer, flag logo, water-resistant shell, packable design.", 199, "Clothing", 25),
    p("Under Armour ColdGear Base Layer", "Dual-layer fabric traps heat, moisture transport system, 4-way stretch.", 55, "Clothing", 70),
    p("Converse Chuck Taylor All Star High", "Canvas upper, OrthoLite insole, vulcanized rubber sole, iconic silhouette.", 65, "Clothing", 130),
    p("Lululemon ABC Jogger Pants", "Anti-Ball Crushing construction, 4-way stretch Warpstreme fabric, hidden zip pocket.", 128, "Clothing", 40),
    p("BOSS Hugo Boss Slim Fit Dress Shirt", "Egyptian cotton, cutaway collar, mother-of-pearl buttons, easy iron.", 128, "Clothing", 35),
    p("Birkenstock Arizona Sandals", "Contoured cork footbed, adjustable buckle straps, suede lined, EVA outsole.", 110, "Clothing", 55),
    p("Canada Goose Expedition Parka", "Arctic Tech shell, 625-fill white duck down, fur-trimmed hood, TEI 5 rating.", 1325, "Clothing", 5),
    p("Lacoste L.12.12 Classic Polo", "Petit piquÃ© cotton, ribbed collar, mother-of-pearl buttons, crocodile logo.", 89.50, "Clothing", 70),
    p("Salomon Speedcross 6 Trail Shoes", "Contagrip MA outsole, Sensifit cradle, quicklace system, aggressive lugs.", 140, "Clothing", 30),
    p("H&M Relaxed Fit Linen Shirt", "100% linen, relaxed fit, camp collar, lightweight for warm weather.", 34.99, "Clothing", 90),
    p("Zara Oversized Wool Blend Coat", "Double-breasted, wool blend, wide lapels, longline silhouette.", 189, "Clothing", 20),
    p("ASICS Gel-Kayano 30 Running Shoes", "4D Guidance System, FF BLAST PLUS cushioning, ASICSGRIP outsole.", 160, "Clothing", 45),
    p("Ralph Lauren Cable-Knit Sweater", "100% cotton cable knit, ribbed trim, crew neck, classic fit.", 125, "Clothing", 30),
    p("G-STAR RAW 3301 Slim Jeans", "Comfort stretch denim, slim fit, 5-pocket styling, signature rivets.", 120, "Clothing", 40),
    p("PUMA RS-X Sneakers", "Running System technology, thick cushioning, retro-futuristic design.", 110, "Clothing", 50),
    p("Barbour Ashby Wax Jacket", "6oz Sylkoil waxed cotton, corduroy collar, tartan lining, two-way zip.", 399, "Clothing", 12),
    p("Nike Tech Fleece Joggers", "Heavyweight double-knit fleece, tapered fit, zip pockets, embroidered Swoosh.", 110, "Clothing", 65),
    p("Diesel T-Diegor Logo T-Shirt", "Organic cotton, crew neck, bold chest logo, relaxed fit.", 55, "Clothing", 80),
    p("Moncler Montcla Down Jacket", "Lacquered nylon laquÃ©, 90/10 goose down, detachable hood, two-way zip.", 1890, "Clothing", 3),
    p("Reebok Classic Leather Shoes", "Soft leather upper, die-cut EVA midsole, high-abrasion rubber outsole.", 75, "Clothing", 70),
    p("Stone Island Compass Badge Sweatshirt", "Garment-dyed cotton fleece, removable compass badge, ribbed trims.", 310, "Clothing", 15),
    p("Wrangler Cowboy Cut Original Fit Jeans", "Heavyweight 13.75oz denim, cowboy cut, broken twill weave, 5-pocket.", 44, "Clothing", 100),
    p("On Cloud 5 Running Shoes", "CloudTec sole, Speedboard, lightweight mesh, Swiss-engineered comfort.", 139.99, "Clothing", 50),
    p("Burberry Vintage Check Scarf", "100% cashmere, iconic check pattern, fringe edges, made in Scotland.", 470, "Clothing", 10),

    # â”€â”€ Home & Kitchen (50 products) â”€â”€
    p("Herman Miller Aeron Chair", "Ergonomic office chair, 8Z Pellicle suspension, PostureFit SL, adjustable arms.", 1805, "Home & Kitchen", 20),
    p("Dyson V15 Detect Cordless Vacuum", "Laser reveals hidden dust, piezo sensor counts particles, up to 60 min runtime.", 749, "Home & Kitchen", 15),
    p("Nespresso Vertuo Plus Coffee Machine", "Centrifusion technology, 5 cup sizes, automatic blend recognition, 30-sec heat-up.", 179, "Home & Kitchen", 40),
    p("Le Creuset Signature Dutch Oven 5.5qt", "Enameled cast iron, superior heat distribution, tight-fitting lid, oven safe to 500Â°F.", 380, "Home & Kitchen", 20),
    p("KitchenAid Artisan Stand Mixer", "10 speeds, 5-quart stainless steel bowl, tilt-head design, 10+ attachments.", 449, "Home & Kitchen", 18),
    p("Vitamix A3500 Ascent Blender", "Variable speed, self-detect containers, 5 program settings, built-in timer.", 649, "Home & Kitchen", 12),
    p("Breville Barista Express Espresso", "Integrated grinder, PID temperature control, steam wand, 54mm portafilter.", 699, "Home & Kitchen", 10),
    p("iRobot Roomba j9+ Robot Vacuum", "PrecisionVision navigation, 3-stage cleaning, auto-empty base, smart mapping.", 799, "Home & Kitchen", 15),
    p("Philips Sonicare 9900 Prestige Toothbrush", "SenseIQ technology, pressure sensor, All Day Clean brush head, travel case.", 299, "Home & Kitchen", 30),
    p("Instant Pot Duo Plus 6-Quart", "9-in-1: pressure cooker, slow cooker, rice cooker, steamer, sautÃ© pan, and more.", 89, "Home & Kitchen", 50),
    p("Dyson Purifier Hot+Cool HP09", "HEPA H13 + carbon filters, senses pollutants, purifies, heats, and cools.", 649, "Home & Kitchen", 10),
    p("Staub Cast Iron Cocotte 5.5qt", "Black matte enamel interior, self-basting spike lid, even heat distribution.", 399, "Home & Kitchen", 15),
    p("Coway Airmega 400S Air Purifier", "Dual HEPA filters, 1560 sq ft coverage, real-time AQI indicator, smart mode.", 549, "Home & Kitchen", 12),
    p("Philips 3200 LatteGo Espresso Machine", "5 coffee varieties, LatteGo milk system, intuitive touch display, AquaClean filter.", 899, "Home & Kitchen", 8),
    p("All-Clad D5 Stainless Steel Fry Pan 12-inch", "5-ply bonded construction, stainless steel cooking surface, oven and broiler safe.", 199, "Home & Kitchen", 25),
    p("Moccamaster KBGV Select Coffee Brewer", "Copper heating element, 6-min brew time, auto drip-stop, BPA-free, made in Netherlands.", 309, "Home & Kitchen", 15),
    p("Casper Original Mattress Queen", "Zoned Support foam, breathable AirScape perforations, 100-night trial.", 1095, "Home & Kitchen", 6),
    p("Weber Genesis E-335 Gas Grill", "3-burner, sear station, side burner, Weber Connect, 669 sq in cooking area.", 1199, "Home & Kitchen", 5),
    p("Ninja Foodi 8-Quart DualZone Air Fryer", "Two independent baskets, 6 cooking functions, DualZone Technology, Match Cook.", 179, "Home & Kitchen", 35),
    p("Tempur-Pedic TEMPUR-Cloud Pillow", "TEMPUR material adapts to head and neck, cooling gel layer, machine washable cover.", 89, "Home & Kitchen", 45),
    p("Zwilling J.A. Henckels Pro 8-inch Chef's Knife", "Special formula steel, ice-hardened Friodur blade, ergonomic handle, full tang.", 169, "Home & Kitchen", 30),
    p("Roomba Combo j9+ Robot Vacuum & Mop", "4-stage cleaning, auto-retract mopping pad, auto-empty & auto-refill.", 1399, "Home & Kitchen", 5),
    p("Smeg 50's Retro Style Toaster 4-Slice", "6 browning levels, self-centering racks, stainless steel body, retro design.", 249, "Home & Kitchen", 20),
    p("Balmuda The Toaster", "Steam technology, precise temperature, 5 modes, compact Japanese design.", 299, "Home & Kitchen", 15),
    p("Brooklinen Luxe Core Sheet Set King", "480 thread count long-staple cotton sateen, buttery smooth, OEKO-TEX certified.", 178, "Home & Kitchen", 25),
    p("Fellow Ode Brew Grinder Gen 2", "64mm flat burrs, single-dose hopper, anti-static technology, magnetic catch.", 299, "Home & Kitchen", 15),
    p("Sonos Beam Gen 2 Soundbar", "Dolby Atmos, Trueplay tuning, HDMI eARC, voice control, compact design.", 449, "Home & Kitchen", 20),
    p("Dyson Airwrap Multi-Styler", "Coanda airflow, 6 attachments, intelligent heat control, for multiple hair types.", 599, "Home & Kitchen", 10),
    p("Yeti Rambler 36oz Bottle", "Double-wall vacuum insulation, 18/8 stainless steel, DuraCoat color, dishwasher safe.", 50, "Home & Kitchen", 100),
    p("Simplehuman Sensor Mirror Pro", "Tru-lux light system, 5x magnification, color-accurate LED, WiFi updates.", 400, "Home & Kitchen", 12),
    p("Lodge Cast Iron Skillet 12-inch", "Pre-seasoned, unparalleled heat retention, oven safe, lifetime durability.", 39.90, "Home & Kitchen", 80),
    p("Nespresso Creatista Plus", "Latte art steam wand, 8 milk texture levels, 3-second heat-up, TFT display.", 599, "Home & Kitchen", 8),
    p("Anthropologie Gleaming Primrose Mirror", "Iron frame with gold finish, decorative detailing, floor-length, 7 feet tall.", 1298, "Home & Kitchen", 4),
    p("West Elm Mid-Century Nightstand", "FSC-certified wood, mid-century modern design, tapered legs, soft-close drawers.", 449, "Home & Kitchen", 10),
    p("Crate & Barrel Gathering Table", "Solid mango wood, natural live-edge, iron base, seats 6-8, hand-finished.", 1599, "Home & Kitchen", 3),
    p("Hisense 55-inch Mini-LED ULED TV", "Full Array Local Dimming, Quantum Dot, Google TV, Dolby Vision IQ, IMAX Enhanced.", 549, "Home & Kitchen", 12),
    p("Shark FlexStyle Air Styling System", "Auto-wrap curlers, oval brush, paddle brush, concentrator, no extreme heat.", 299, "Home & Kitchen", 20),
    p("Oxo Good Grips 3-Piece Mixing Bowl Set", "Stainless steel, non-slip base, pour spout, measurement markings, dishwasher safe.", 49.99, "Home & Kitchen", 60),
    p("Eufy RoboVac G30 Edge", "Smart Dynamic Navigation 2.0, 2000Pa suction, BoostIQ, boundary strips.", 229, "Home & Kitchen", 25),

    # â”€â”€ Sports & Outdoors (40 products) â”€â”€
    p("Peloton Bike+", "24-inch rotating HD screen, auto-follow resistance, Apple GymKit, live & on-demand classes.", 2495, "Sports & Outdoors", 5),
    p("Yeti Tundra 45 Hard Cooler", "Rotomolded construction, PermaFrost insulation, bearfoot non-slip feet, T-Rex lid latches.", 325, "Sports & Outdoors", 15),
    p("Garmin Edge 1040 Solar Cycling Computer", "Solar charging, multi-band GPS, power guide, ClimbPro, training status.", 599, "Sports & Outdoors", 10),
    p("Hydro Flask 32oz Wide Mouth", "TempShield double-wall insulation, 18/8 stainless steel, BPA-free, lifetime warranty.", 44.95, "Sports & Outdoors", 100),
    p("Osprey Atmos AG 65L Backpack", "Anti-Gravity suspension, adjustable harness, integrated rain cover, Stow-on-the-Go poles.", 290, "Sports & Outdoors", 15),
    p("Theragun PRO Plus", "Percussive therapy, 6 attachments, QuietForce Technology, OLED screen, Bluetooth.", 499, "Sports & Outdoors", 20),
    p("Bowflex SelectTech 552 Dumbbells", "Adjustable 5-52.5 lbs, dial system, replaces 15 sets, compact design.", 429, "Sports & Outdoors", 12),
    p("TRX PRO4 Suspension Training System", "6 adjustable anchor points, locking carabiner, XMount, door anchor, mesh bag.", 249, "Sports & Outdoors", 25),
    p("Manduka PRO Yoga Mat 71-inch", "6mm thick, closed-cell PVC, lifetime guarantee, high-density cushion, non-slip.", 120, "Sports & Outdoors", 35),
    p("Coleman Sundome 4-Person Tent", "WeatherTec system, 1 large door, E-port, setup in 10 min, dark room technology.", 89, "Sports & Outdoors", 30),
    p("Black Diamond Spot 400-R Headlamp", "400 lumens, USB-C rechargeable, PowerTap, 3 brightness levels, red night vision.", 49.95, "Sports & Outdoors", 50),
    p("NordicTrack Commercial 1750 Treadmill", "14-inch HD touchscreen, iFIT, auto-adjust incline/decline, FlexSelect cushioning.", 1799, "Sports & Outdoors", 4),
    p("Patagonia Black Hole Duffel 55L", "100% recycled body, weather-resistant, U-shaped opening, padded shoulder straps.", 149, "Sports & Outdoors", 20),
    p("ROKA Maverick Pro II Wetsuit", "Yamamoto SCS neoprene, zero drag coating, flexible arm panels, buoyancy zones.", 450, "Sports & Outdoors", 8),
    p("Garmin Forerunner 965 GPS Watch", "AMOLED display, Training Readiness, Race Widget, multi-band GPS, 23-day battery.", 599, "Sports & Outdoors", 12),
    p("Hyperice Hypervolt 2 Pro", "Percussion massage, Quiet Glide technology, 5 head attachments, Bluetooth.", 329, "Sports & Outdoors", 18),
    p("REI Co-op Flash 55 Pack", "Ultralight 2 lbs 5 oz, PFC-free DWR, load lifter straps, hydration compatible.", 199, "Sports & Outdoors", 15),
    p("Concept2 Model D Indoor Rower", "PM5 performance monitor, air resistance flywheel, ergonomic handle, easy storage.", 990, "Sports & Outdoors", 6),
    p("Stanley Adventure Quencher 40oz", "Double-wall vacuum, FlowState lid, fits cup holders, dishwasher safe.", 35, "Sports & Outdoors", 150),
    p("Sea to Summit Ultralight Insulated Sleeping Pad", "Thermolite insulation, R-value 3.1, Air Sprung Cells, packs to 750mL.", 189, "Sports & Outdoors", 15),
    p("Wahoo KICKR V6 Smart Trainer", "Direct-drive, 2200W max, 1% accuracy, ERG mode, WiFi & ANT+/BLE.", 1299, "Sports & Outdoors", 5),
    p("Nemo Hornet Elite 2P Ultralight Tent", "2 lbs, DAC Featherlite poles, Divvy Sack stuff system, Flybar venting.", 449, "Sports & Outdoors", 8),
    p("Fitbit Charge 6 Fitness Tracker", "Built-in GPS, heart rate, EDA, SpO2, 40+ exercise modes, 7-day battery.", 159, "Sports & Outdoors", 40),
    p("WHOOP 4.0 Fitness Strap", "Strain tracking, recovery score, sleep coaching, HRV, 5-day battery, waterproof.", 239, "Sports & Outdoors", 20),
    p("Kelty Cosmic 20 Sleeping Bag", "DriDown 600-fill, EN-tested 20Â°F, 2 lbs 11 oz, natural fit footbox.", 159, "Sports & Outdoors", 18),
    p("Envy Prodigy S9 Pro Scooter", "HIC compression, 120mm wheels, 4130 chromoly bars, 6061 aluminum deck.", 249, "Sports & Outdoors", 12),
    p("Lifeline Power Wheel Ab Roller", "Dual wheels for stability, ergonomic handles, knees-to-standing progression.", 39.99, "Sports & Outdoors", 60),
    p("Altra Lone Peak 7 Trail Runners", "FootShape toe box, Balanced Cushioning, MaxTrac outsole, 4-point GaiterTrap.", 140, "Sports & Outdoors", 25),
    p("Petzl Grigri+ Belay Device", "Assisted braking, two modes (top-rope/lead), anti-panic handle, steel cam.", 124.95, "Sports & Outdoors", 15),
    p("Rogue Echo Bike", "Air resistance fan, belt-driven, LCD console, steel frame, 127 lb, adjustable seat.", 795, "Sports & Outdoors", 6),

    # â”€â”€ Books (30 products) â”€â”€
    p("Atomic Habits by James Clear", "Tiny changes, remarkable results. A proven framework for improving every day.", 16.99, "Books", 200),
    p("The Pragmatic Programmer 20th Anniversary", "From journeyman to master. Classic software development guide, updated edition.", 49.99, "Books", 60),
    p("Designing Data-Intensive Applications", "By Martin Kleppmann. The big ideas behind reliable, scalable, and maintainable systems.", 45.99, "Books", 40),
    p("Clean Code by Robert C. Martin", "A handbook of agile software craftsmanship. Writing readable, maintainable code.", 39.99, "Books", 50),
    p("Sapiens: A Brief History of Humankind", "By Yuval Noah Harari. How Homo sapiens came to dominate the world.", 18.99, "Books", 150),
    p("Thinking, Fast and Slow by Daniel Kahneman", "Nobel laureate on the two systems that drive the way we think and make decisions.", 17.99, "Books", 120),
    p("System Design Interview Vol 1 by Alex Xu", "An insider's guide for large-scale system design questions. Step-by-step framework.", 35.99, "Books", 70),
    p("Educated by Tara Westover", "A memoir about growing up in a survivalist family and the power of education.", 14.99, "Books", 100),
    p("The Psychology of Money by Morgan Housel", "Timeless lessons on wealth, greed, and happiness through short stories.", 16.99, "Books", 130),
    p("Dune by Frank Herbert", "The epic science fiction masterpiece. A tale of politics, religion, and ecology.", 12.99, "Books", 90),
    p("Project Hail Mary by Andy Weir", "A lone astronaut must save Earth. From the author of The Martian.", 16.99, "Books", 80),
    p("Deep Work by Cal Newport", "Rules for focused success in a distracted world. Systematic approach to deep work.", 15.99, "Books", 100),
    p("The Art of War by Sun Tzu", "Ancient Chinese military treatise on strategy. Timeless principles for competition.", 8.99, "Books", 200),
    p("Cracking the Coding Interview", "189 programming questions & solutions. 6th edition by Gayle Laakmann McDowell.", 39.95, "Books", 50),
    p("The Lean Startup by Eric Ries", "How today's entrepreneurs use continuous innovation to create successful businesses.", 16.99, "Books", 80),
    p("Steve Jobs by Walter Isaacson", "The exclusive biography based on 40+ interviews with Jobs and 100+ others.", 19.99, "Books", 60),
    p("The Alchemist by Paulo Coelho", "A mystical story about following your dreams. A worldwide bestseller.", 11.99, "Books", 180),
    p("Zero to One by Peter Thiel", "Notes on startups, or how to build the future. Contrarian thinking on innovation.", 16.99, "Books", 70),
    p("The 48 Laws of Power by Robert Greene", "A modern Machiavellian guide to power, seduction, and strategy.", 18.99, "Books", 90),
    p("1984 by George Orwell", "The dystopian novel about totalitarianism, surveillance, and truth. A timeless classic.", 9.99, "Books", 250),
    p("Meditations by Marcus Aurelius", "Personal writings of the Roman Emperor. Stoic philosophy for everyday life.", 7.99, "Books", 200),
    p("Good to Great by Jim Collins", "Why some companies make the leap and others don't. Built-to-last research.", 22.99, "Books", 60),
    p("Algorithms by Robert Sedgewick", "Comprehensive introduction to algorithms and data structures. 4th edition.", 69.99, "Books", 30),
    p("Can't Hurt Me by David Goggins", "Master your mind and defy the odds. The story of one of the toughest men alive.", 18.99, "Books", 100),
    p("Why We Sleep by Matthew Walker", "Unlocking the power of sleep and dreams. A neuroscientist's exploration.", 17.99, "Books", 70),
    p("The Design of Everyday Things by Don Norman", "Revised and expanded edition. The psychology behind good and bad design.", 19.99, "Books", 40),
    p("Shoe Dog by Phil Knight", "A memoir by the creator of Nike. The story behind the swoosh.", 16.99, "Books", 80),
    p("Never Split the Difference by Chris Voss", "Negotiating as if your life depended on it. FBI hostage negotiator tactics.", 17.99, "Books", 90),
    p("Outliers by Malcolm Gladwell", "The story of success. Why some people succeed and how cultural legacy matters.", 16.99, "Books", 100),
    p("Range by David Epstein", "Why generalists triumph in a specialized world. The power of broad experience.", 16.99, "Books", 60),

    # â”€â”€ Beauty & Personal Care (25 products) â”€â”€
    p("Dyson Supersonic Hair Dryer", "Intelligent heat control, 4 styling attachments, fast drying, lightweight design.", 429, "Beauty", 15),
    p("La Mer Moisturizing Cream 2oz", "Miracle Broth infused, cell-renewing Miracle Broth, transforms skin, ultra-rich.", 380, "Beauty", 10),
    p("Olaplex No.3 Hair Perfector", "Bond-building treatment, reduces breakage, strengthens hair, salon-quality results.", 30, "Beauty", 80),
    p("SK-II Facial Treatment Essence 230ml", "Over 90% Pitera, natural bio-ingredient, crystal clear skin, anti-aging.", 229, "Beauty", 15),
    p("Tatcha The Water Cream", "Oil-free moisturizer, Japanese wild rose, leopard lily, weightless hydration.", 68, "Beauty", 30),
    p("Drunk Elephant C-Firma Fresh Day Serum", "15% L-ascorbic acid, pumpkin ferment, antioxidant day serum, brightening.", 78, "Beauty", 25),
    p("Charlotte Tilbury Pillow Talk Lipstick", "Iconic nude-pink shade, diamond powder, 3D lips, long-lasting matte finish.", 34, "Beauty", 60),
    p("Tom Ford Black Orchid EDP 100ml", "Luxurious and sensual fragrance, black truffle, ylang-ylang, patchouli.", 176, "Beauty", 20),
    p("NÃ©cessaire The Body Wash Eucalyptus", "Clean body care, vitamins + niacinamide, dermatologist-tested, fragrance from oils.", 25, "Beauty", 50),
    p("Paula's Choice 2% BHA Liquid Exfoliant", "Salicylic acid, unclogs pores, smooths wrinkles, evens skin tone, gentle formula.", 32, "Beauty", 70),
    p("Augustinus Bader The Rich Cream 50ml", "TFC8 technology, stem cell complex, anti-aging, clinically proven results.", 290, "Beauty", 8),
    p("Dior Sauvage Eau de Parfum 100ml", "Ambroxan and vanilla, calabrian bergamot, fresh and raw masculinity.", 150, "Beauty", 25),
    p("Glossier Boy Brow", "Fluffy, full-looking brows, conditioning formula, flexible hold, 4 shades.", 17, "Beauty", 100),
    p("CeraVe Moisturizing Cream 19oz", "3 essential ceramides, MVE delivery technology, fragrance-free, non-comedogenic.", 18.99, "Beauty", 150),
    p("GHD Platinum+ Hair Straightener", "Predictive ultra-zone technology, optimum 365Â°F, wishbone hinge, 20-sec heat-up.", 279, "Beauty", 20),
    p("NARS Radiant Creamy Concealer", "Medium buildable coverage, luminous finish, multi-active botanical blend, crease-proof.", 31, "Beauty", 55),
    p("Chanel No. 5 EDP 100ml", "The iconic fragrance. Aldehydes, jasmine, rose, sandalwood, and vanilla.", 165, "Beauty", 15),
    p("The Ordinary Niacinamide 10% + Zinc 1%", "High-strength vitamin and mineral blemish formula, oil control, pore reduction.", 5.90, "Beauty", 200),
    p("Rare Beauty Soft Pinch Liquid Blush", "Weightless, long-lasting, dewy finish, buildable formula by Selena Gomez.", 23, "Beauty", 80),
    p("Jo Malone Wood Sage & Sea Salt Cologne 100ml", "Earthy, mineral, wind-swept freshness, ambrette seeds, sea salt, sage.", 142, "Beauty", 18),
    p("Sunday Riley Good Genes Lactic Acid Treatment", "All-in-one AHA, anti-aging, brightening, clarifying, exfoliating treatment.", 85, "Beauty", 22),
    p("MAC Ruby Woo Retro Matte Lipstick", "Iconic blue-red matte, long-wearing, non-feathering, full coverage.", 21, "Beauty", 90),
    p("KÃ©rastase Elixir Ultime Hair Oil", "Camellia, argan, marula, maize oils, shine, nourishment, heat protection.", 56, "Beauty", 35),
    p("Fenty Beauty Pro Filt'r Foundation", "42 shades, soft matte, oil-free, climate-adaptive, buildable medium coverage.", 40, "Beauty", 50),
    p("Moroccanoil Treatment Original 100ml", "Argan oil-infused, conditions, styles, and finishes hair, color-safe.", 48, "Beauty", 40),

    # â”€â”€ Toys & Games (20 products) â”€â”€
    p("LEGO Technic Lamborghini SiÃ¡n FKP 37", "3696 pieces, V12 engine with moving pistons, scissor doors, 1:8 scale.", 449, "Toys & Games", 8),
    p("Ravensburger 3D Puzzle Eiffel Tower", "216 pieces, 18.5 inches tall, hinged plastic pieces, no glue required.", 29.99, "Toys & Games", 30),
    p("Monopoly: Disney Edition", "Explore Disney attractions, collectible tokens, pop-up castle, themed properties.", 39.99, "Toys & Games", 40),
    p("LEGO Star Wars Millennium Falcon UCS", "7541 pieces, detailed interior, rotating gun turrets, display stand, minifigures.", 849, "Toys & Games", 3),
    p("Hot Wheels Ultimate Garage Playset", "100+ car storage, race track, robo-dinosaur attack, city theme, motorized.", 119, "Toys & Games", 15),
    p("Settlers of Catan Board Game", "Trade, build, settle. Strategy game for 3-4 players, resource management.", 44, "Toys & Games", 50),
    p("Dungeons & Dragons Starter Set 5e", "Everything you need to play D&D, pre-generated characters, adventure book, dice.", 19.99, "Toys & Games", 60),
    p("Nerf Elite 2.0 Eaglepoint RD-8", "Detachable scope, barrel, stock, 8-dart drum, slam-fire action.", 24.99, "Toys & Games", 45),
    p("Ticket to Ride Board Game", "Cross-country train adventure game, 2-5 players, collect cards and claim routes.", 44.99, "Toys & Games", 40),
    p("LEGO Architecture Skyline Collection: Paris", "649 pieces, Eiffel Tower, Louvre, Champs-Ã‰lysÃ©es, Arc de Triomphe.", 49.99, "Toys & Games", 25),
    p("Codenames Board Game", "Secret agents, 2 teams, give one-word clues, spy-themed party game, 2-8 players.", 19.95, "Toys & Games", 55),
    p("Magna-Tiles Clear Colors 100-Piece Set", "Magnetic building tiles, STEM learning, 3D construction, ages 3+.", 119, "Toys & Games", 20),
    p("Risk Global Domination Board Game", "Strategic conquest, 5 continents, secret missions, 2-5 players, classic.", 33.99, "Toys & Games", 35),
    p("Rubik's Cube 3x3 Speed Cube", "Original speed cube, smooth turning, corner-cutting, competition-ready.", 12.99, "Toys & Games", 100),
    p("Exploding Kittens Card Game", "Highly strategic, kitty-powered party game, 2-5 players, NSFW edition available.", 19.99, "Toys & Games", 60),
    p("LEGO Ideas Tree House 21318", "3036 pieces, interchangeable summer/autumn leaves, 4 tree-top cabins, nature theme.", 249, "Toys & Games", 6),
    p("Wingspan Board Game", "Engine-building bird game, 170 unique bird cards, beautiful artwork, 1-5 players.", 55, "Toys & Games", 25),
    p("Barbie Dreamhouse 2024", "3.75ft tall, 10 rooms, 75+ pieces, pool, slide, elevator, working lights & sounds.", 199, "Toys & Games", 10),
    p("Azul Board Game", "Tile-laying strategy, Portuguese azulejos theme, 2-4 players, pattern building.", 34.99, "Toys & Games", 30),
    p("Play-Doh Ultimate Color Collection 65-Pack", "65 cans of Play-Doh, non-toxic, assorted colors, great party activity.", 19.99, "Toys & Games", 80),

    # â”€â”€ Automotive (15 products) â”€â”€
    p("Meguiar's Ultimate Compound", "Removes oxidation, scratches, water spots. Micro-abrasive technology, clear coat safe.", 12.99, "Automotive", 80),
    p("Chemical Guys Honeydew Snow Foam", "Extreme suds, pH balanced, safe on wax and sealants, 1-gallon concentrate.", 24.99, "Automotive", 60),
    p("NOCO Boost Plus GB40 Jump Starter", "1000A 12V, ultrasafe lithium, 6L gas/3L diesel, USB power bank, LED flashlight.", 99, "Automotive", 35),
    p("Thinkware U3000 4K Dash Cam", "4K front, 2K rear, starvis 2 sensor, radar, parking surveillance, built-in GPS.", 499, "Automotive", 10),
    p("Michelin CrossClimate2 Tire 225/65R17", "All-weather performance, 60K mile warranty, V-ramp sipes, Flex-Ice compound.", 189, "Automotive", 40),
    p("WeatherTech FloorLiner Set", "Custom-fit, high-density tri-extruded material, raised edges, laser-measured.", 149, "Automotive", 25),
    p("Ceramic Pro Rain Windshield Coating", "Super hydrophobic, nanoceramic, improves visibility, 12-month durability.", 49.99, "Automotive", 40),
    p("Milwaukee M12 FUEL 3/8 Stubby Impact Wrench", "Compact design, 250 ft-lbs, REDLINK PLUS, auto shut-off, bare tool.", 179, "Automotive", 20),
    p("Gyeon QÂ² Mohs+ Ceramic Coating Kit", "SiO2 ceramic coating, 24-month durability, self-cleaning effect, UV protection.", 79.99, "Automotive", 15),
    p("Viofo A139 Pro 3-Channel Dash Cam", "4K+1080P+1080P, starvis 2, GPS, WiFi, parking mode, 256GB max.", 349, "Automotive", 12),
    p("CTEK MXS 5.0 Battery Charger", "Fully automatic 8-step charger, temperature compensation, AGM/cold mode.", 89, "Automotive", 30),
    p("Adam's Polishes Graphene Ceramic Spray", "Graphene-infused, 9H hardness, hydrophobic, 12+ month protection, easy apply.", 29.99, "Automotive", 50),
    p("Carcarez Microfiber Towels 50-Pack", "16x16 inches, 380 GSM, lint-free, scratch-free, edgeless design.", 29.99, "Automotive", 70),
    p("Autel MaxiCOM MK808BT Pro OBD2 Scanner", "All-system diagnostics, 28+ reset services, wireless Bluetooth, bi-directional.", 349, "Automotive", 10),
    p("K&N Cold Air Intake Kit", "Guaranteed power gains, washable filter, 50-state legal, CARB approved.", 349, "Automotive", 8),

    # â”€â”€ Grocery & Gourmet (15 products) â”€â”€
    p("Nespresso VertuoLine Variety Pack 40ct", "4 blends of Vertuo capsules, Odacio, Stormio, Melozio, and Giornio.", 42, "Grocery", 80),
    p("Manuka Health MGO 400+ Manuka Honey 500g", "Authentic New Zealand manuka, tested & certified MGO level, raw & natural.", 59, "Grocery", 25),
    p("Ghirardelli Intense Dark 86% Cacao Squares", "Premium dark chocolate, 86% cacao, non-GMO, individually wrapped squares.", 7.99, "Grocery", 100),
    p("Lavazza Super Crema Espresso Beans 2.2lb", "Medium roast, creamy taste, hazelnut and brown sugar notes, blend of Arabica and Robusta.", 19.99, "Grocery", 60),
    p("Liquid Death Mountain Water 12-Pack", "Infinitely recyclable aluminum, Austrian Alps spring water, murder your thirst.", 18.99, "Grocery", 90),
    p("Graza Drizzle Extra Virgin Olive Oil", "Single-origin Picual, squeeze bottle, finishing oil, from Spain.", 19.99, "Grocery", 50),
    p("Athletic Brewing Run Wild Non-Alcoholic IPA 6-Pack", "Craft non-alcoholic IPA, 65 calories, citrus and floral aroma, award-winning.", 12.99, "Grocery", 40),
    p("Maldon Sea Salt Flakes 8.5oz", "Hand-harvested, pyramid-shaped crystals, clean flavor, finishing salt.", 8.99, "Grocery", 70),
    p("RXBAR Protein Bars Variety Pack 12ct", "12g protein, no B.S., egg whites, dates, nuts, simple clean ingredients.", 24.99, "Grocery", 65),
    p("Chamberlain Coffee Social Dog Blend Ground", "Medium roast, notes of chocolate and hazelnut, single-origin, organic.", 15.99, "Grocery", 45),
    p("Mike's Hot Honey 10oz", "Infused with chili peppers, perfect on pizza, chicken, and cheese, pure honey.", 9.99, "Grocery", 80),
    p("Califia Farms Oat Barista Blend 32oz", "Creamy oat milk, froths perfectly, non-GMO, vegan, shelf-stable.", 5.99, "Grocery", 100),
    p("Hu Dark Chocolate Bars Variety 8-Pack", "Simple ingredients, no refined sugar, vegan, paleo, organic cacao.", 34.99, "Grocery", 35),
    p("Nuun Sport Electrolyte Tablets Variety 4-Pack", "Clean hydration, effervescent tablets, no sugar, 300mg electrolytes.", 23.96, "Grocery", 55),
    p("Bonne Maman Preserves Gift Set 5-Jar", "French preserves, raspberry, strawberry, apricot, cherry, blueberry.", 29.99, "Grocery", 30),

    # â”€â”€ Gaming (15 products) â”€â”€
    p("SteelSeries Arctis Nova Pro Wireless Headset", "Active noise cancellation, dual wireless, infinity battery, hi-res audio.", 349, "Gaming", 15),
    p("Secretlab Titan Evo 2022 Gaming Chair", "4-way L-ADAPT lumbar, pebble seat base, magnetic headrest, NEO Hybrid Leatherette.", 519, "Gaming", 10),
    p("SCUF Instinct Pro Controller", "4 rear paddles, adjustable triggers, interchangeable thumbsticks, performance grip.", 219, "Gaming", 20),
    p("BenQ ZOWIE XL2546K 240Hz Monitor", "24.5-inch, DyAc+, XL Setting to Share, S Switch, esports certified.", 499, "Gaming", 8),
    p("Elgato HD60 X Capture Card", "4K60 HDR10 passthrough, 1080p60 capture, VRR, USB 3.0, zero-lag passthrough.", 199, "Gaming", 18),
    p("HyperX Cloud III Wireless Headset", "DTS Spatial Audio, 120-hour battery, 53mm drivers, memory foam ear cushions.", 149, "Gaming", 25),
    p("Logitech G Pro X Superlight 2", "60g ultralight, HERO 2 sensor, LIGHTFORCE switches, LIGHTSPEED wireless.", 159, "Gaming", 30),
    p("Razer Huntsman V3 Pro Keyboard", "Analog optical switches, rapid trigger, polling at 8000Hz, magnetic wrist rest.", 249, "Gaming", 12),
    p("Samsung Odyssey OLED G8 34-inch", "QD-OLED, 175Hz, 0.03ms, VESA DisplayHDR True Black 400, AMD FreeSync Premium Pro.", 1299, "Gaming", 6),
    p("Lian Li O11 Dynamic EVO PC Case", "Dual-chamber design, modular I/O, tempered glass, up to 360mm radiator, E-ATX.", 169, "Gaming", 15),
    p("NZXT Kraken Elite 360 AIO Cooler", "2.36-inch LCD screen, 7th gen Asetek pump, F120P fans, CAM software.", 299, "Gaming", 10),
    p("Glorious GMMK Pro 75% Keyboard", "Gasket-mounted, aluminum frame, rotary knob, hot-swappable, RGB per-key.", 169, "Gaming", 20),
    p("Corsair iCUE Link H150i RGB AIO", "Modular daisy-chain cables, 360mm radiator, AF120 RGB fans, zero RPM mode.", 189, "Gaming", 14),
    p("Noblechairs HERO Gaming Chair", "Cold foam upholstery, 4D armrests, integrated lumbar, steel frame, 150kg capacity.", 489, "Gaming", 8),
    p("RODE X XDM-100 Dynamic USB Microphone", "Dynamic capsule, Revolution preamp, DSP, APHEX processing, zero-latency monitoring.", 299, "Gaming", 12),

    # â”€â”€ Office & Stationery (15 products) â”€â”€
    p("Apple Magic Keyboard with Touch ID", "Scissor mechanism, Touch ID sensor, backlit keys, USB-C, macOS integration.", 199, "Office", 30),
    p("Moleskine Classic Notebook Large", "Hard cover, 240 ruled pages, acid-free paper, elastic closure, bookmark ribbon.", 22.95, "Office", 80),
    p("Pilot Metropolitan Fountain Pen", "Medium nib, brass barrel, squeeze converter included, balanced weight.", 18.75, "Office", 50),
    p("CalDigit TS4 Thunderbolt 4 Dock", "18 ports, 98W charging, 8K display, 2.5GbE ethernet, SD 4.0, front USB-C.", 399, "Office", 12),
    p("BenQ ScreenBar Halo Monitor Light", "Backlight for ambient lighting, auto-dimming, wireless controller, no screen glare.", 179, "Office", 25),
    p("Leuchtturm1917 A5 Dotted Bullet Journal", "249 numbered pages, dotted grid, index, future log, thread-bound, ink-proof paper.", 24.95, "Office", 60),
    p("Logitech MX Keys S Keyboard", "Low-profile, smart backlighting, PerfectStroke keys, multi-device, USB-C charging.", 109, "Office", 35),
    p("Grovemade Desk Shelf System", "Solid hardwood, steel brackets, cable management, monitor riser, premium finish.", 250, "Office", 10),
    p("Twelve South BookArc for MacBook", "Vertical stand, space-saving, airflow design, silicone insert, aluminum.", 49.99, "Office", 30),
    p("Lamy Safari Fountain Pen", "ABS plastic body, ergonomic grip, steel nib, snap cap, ink window.", 30, "Office", 45),
    p("Rain Design mStand Laptop Stand", "Aluminum, 6-inch elevation, cable management, tilted design, 10-inch base.", 49.99, "Office", 25),
    p("Tombow Dual Brush Pen Set 10-Pack", "Flexible brush tip + fine tip, water-based, blendable, acid-free, odorless.", 29.99, "Office", 50),
    p("Bellroy Tech Kit Compact", "Woven fabric, magnetic closure, elastic loops, zippered pocket, EDC organizer.", 49, "Office", 35),
    p("Keychron K3 Pro Low-Profile Keyboard", "75% layout, Gateron low-profile switches, QMK/VIA, wireless, slim aluminum frame.", 109, "Office", 20),
    p("Caran d'Ache 849 Ballpoint Pen", "Hexagonal aluminum body, Goliath refill, Swiss-made, iconic design.", 35, "Office", 40),
]

async def seed():
    client = AsyncIOMotorClient(MONGODB_URI)
    db = client[DB_NAME]

    print("Clearing existing products...")
    await db.products.delete_many({})

    print(f"Inserting {len(PRODUCTS)} products...")
    await db.products.insert_many(PRODUCTS)

    print("Dropping existing text indexes if any...")
    try:
        indexes = await db.products.list_indexes().to_list(None)
        for idx in indexes:
            if "_fts" in idx["key"]:
                await db.products.drop_index(idx["name"])
    except Exception as e:
        print(f"No index to drop: {e}")

    print("Creating text index for search...")
    await db.products.create_index([("name", "text"), ("description", "text"), ("category", "text")])

    print(f"Seed complete! Total products: {len(PRODUCTS)}")
    client.close()

if __name__ == "__main__":
    asyncio.run(seed())

